- src/reader/PancakeV3VaultReader.sol
> [main][fix] wrong feeGrowth calculation

- deploy/av-manager/config/set-withdrawal-fee.ts
- package.json
> [main][feat] set withdrawal fee bps script

- .mainnet.json
- deploy/file-helper/config-file-helper.ts
- deploy/interfaces.ts
> [main][chore] token addresses

- .mainnet.json
- deploy/config/transfer-ownership.ts
- deploy/interfaces.ts
- package.json
- Add transfer ownership script
- For security purpose
> [main][chore] transfer AV ownership

- .mainnet.json
> [main][chore] update .mainnet.json

- .mainnet.json
- .openzeppelin/bsc.json
- deploy/av-manager/config/open-vault.ts
- deploy/vault-oracle/config/set-price-feed.ts
- deploy/worker/deploy/pancake-v3-worker.ts
> [main][deploy] N-USDCUSDT01-PCS1 vault

- .mainnet.json
- deploy/av-manager/config/open-vault.ts
- deploy/file-helper/config-file-helper.ts
- deploy/interfaces.ts
- deploy/worker/deploy/pancake-v3-worker.ts
> [main][chore]  re structure mainnet.json

- .mainnet.json
- .openzeppelin/bsc.json
- deploy/av-manager/config/open-vault.ts
- deploy/vault-oracle/config/set-price-feed.ts
- deploy/worker/deploy/pancake-v3-worker.ts
> [main][deploy] Deploy L-ETHBTCB25-PCS1

- deploy/av-manager/config/set-capacity.ts
> [main][deploy] Increased vaults capacity

- .github/workflows/test-on-dispatch.yml
- .github/workflows/test-on-push.yml
- .mainnet.json
- deploy/config/accept-ownership.ts
- deploy/config/transfer-ownership.ts
- deploy/services/multisig/gnosis-safe/index.ts
- deploy/services/multisig/interface.ts
- package.json
- yarn.lock
> [main][feat] transfer & accept ownership script

- .github/workflows/test-on-dispatch.yml
- .github/workflows/test-on-push.yml
> [main][chore] change RPC url to secrets

- .openzeppelin/bsc.json
- src/executors/PCSV3Executor01.sol
- test/pcs-v3-executor-01/PCSV3Executor01_Deleverage.t.sol
- change deleverage function to account for worker undeployed fund
> [main][feat]deleverage function account for worker undeployed fund

- .mainnet.json
> [main][chore] update mainnet.json

- deploy/av-manager/config/set-max-leverage.ts
- package.json
- add set max leverage script
- to set max leverage for specific vault
> [main][feat] set max leverage script

- .mainnet.json
- .openzeppelin/bsc.json
- deploy/av-manager/config/set-withdrawal-fee.ts
> [main][deploy] Upgrade a new executor

- src/executors/PCSV3Executor01.sol
Add usage of safe cast
Code integrity
> [main][feat]: add safe cast

- deploy/av-manager/config/open-vault.ts
- deploy/worker/deploy/pancake-v3-worker.ts
> [main][chore] refactor open vault script

- .mainnet.json
- .openzeppelin/bsc.json
- deploy/av-manager/config/set-max-leverage.ts
> [main][deploy] Set lev limit

- .mainnet.json
> [main][chore] add L-BTCBBNB05-PCS1

- deploy/av-manager/config/set-management-fee.ts
- deploy/av-manager/config/set-withdrawal-fee.ts
- package.json
> [main][feat] set management fee script

- .openzeppelin/bsc.json
- deploy/utils/force-import.ts
- deploy/worker/upgrade/pancake-v3-worker.ts
- package.json
- src/workers/PancakeV3Worker.sol
- test/pancake-v3-worker/PancakeV3Worker_Harvest.t.sol
> [main][fix] skip harvest routine when position liquidity is zero

- deploy/av-manager/config/set-withdrawal-fee.ts
- foundry.toml
> [main][deploy] turn on withdrawal fee

- .openzeppelin/bsc.json
- deploy/av-manager/upgrade/av-manager.ts
- deploy/utils/force-import.ts
- package.json
- src/AutomatedVaultManager.sol
- test/automated-vault-manager/AutomatedVaultManager_Setters.t.sol
> [main][fix] AVManager setManagementFee

- src/AutomatedVaultManager.sol
- test/automated-vault-manager/AutomatedVaultManager_Deposit.t.sol
Add a priv. function for the vault manager to pause the deposit
Prevent vaults' exposure dilution due to large deposit
> [main][feat] Allow manager to pause the deposit

- deploy/av-manager/config/set-max-leverage.ts
> [main][deploy] Adjust lev

- src/AutomatedVaultManager.sol
- test/automated-vault-manager/AutomatedVaultManager_Deposit.t.sol
- test/automated-vault-manager/AutomatedVaultManager_Setters.t.sol
Allow manager to set its own capacity
> feat: allow manager to set cap
